app/models/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()

def init_app(app):
    db.init_app(app)
    migrate.init_app(app, db)

app/models/user.py
from flask_restful import reqparse
from sqlalchemy_serializer import SerializerMixin
from werkzeug.security import generate_password_hash, check_password_hash


from app.models import db


parser = reqparse.RequestParser()
parser.add_argument(
	'name',
	type=str,
	help='Name of the new user.'
)
parser.add_argument(
	'email',
	type=str,
	help='E-Mail of the new user.'
)
parser.add_argument(
	'password',
	type=str,
	help='Password of the new user.'
)

class User(db.Model, SerializerMixin):
	
	serialize_only = ('id', 'name', 'email')

	id = db.Column(
		db.Integer,
		primary_key=True
	)
	
	name = db.Column(
		db.String(40),
		unique=True,
		nullable=False
	)

	password_hash = db.Column(
		db.String(88)
	)

	email = db.Column(
		db.String(40),
		unique=True
	)

	def set_password(self, password):
		self.password_hash = generate_password_hash(
			password,
			method='sha256'
		)

	def check_password(self, password):
		return check_password_hash(self.password_hash, password)

	def __repr__(self):
		return "<User %r>" % (self.name)

app/forms/login.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, Length, Email, Optional

class LoginForm(FlaskForm):
	username = StringField(validators=[InputRequired(), Length(1, 64)])
	password = PasswordField(validators=[InputRequired(), Length(min=8, max=72)])

app/__init__.py
from flask import Flask
from . import auth, commands, models, routes, resources

def create_app():
	app = Flask(__name__)
	app.config.from_object('config.Config')
	
	models.init_app(app)
	auth.init_app(app)
	resources.init_app(app)
	routes.init_app(app)
	commands.init_app(app)
	
	return app

app/commands/__init__.py
from . import db_command
from . import user_command


def init_app(app):
	app.cli.add_command(user_command.user)

app/resources/__init__.py
from flask_restful import Api


from .auth_resource import AuthResource
from .user_resource import UserResource, UsersResource

api = Api()

def init_app(app):
	api.add_resource(AuthResource, '/api/auth/')
	
	api.add_resource(UserResource, '/api/user/<int:id>')
	api.add_resource(UsersResource, '/api/user/')

	api.init_app(app)

app/routes/__init__.py
from . import index, auth, control

def init_app(app):
    app.register_blueprint(index.bp)
    app.register_blueprint(auth.bp)
    app.register_blueprint(control.bp)

app/routes/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for,request
from flask_jwt_extended import create_access_token, set_access_cookies, unset_jwt_cookies, current_user, jwt_required

from app.forms.login import LoginForm
from app.models.user import User


bp = Blueprint('auth', __name__)

@bp.route("/login", methods=['GET', 'POST'])
@jwt_required(optional=True)
def login():
	form = LoginForm()
	
	if current_user:
		return redirect(url_for('control.dashboard'))

	if request.method=="POST":
		user = User().query.filter_by(name=form.username.data).first()
		if user is not None: 
			if user.check_password(form.password.data):
				response = redirect(url_for('control.dashboard'))
				access_token = create_access_token(identity=user)
				set_access_cookies(response,access_token)
				return response
			else:
				flash("Invalid Username or password!", "danger")
		else:
			flash("Invalid Username or password!", "danger")

	return render_template("auth.html", form=form)
	

@bp.route("/logout", methods=['GET', 'POST'])
def logout():
	response = redirect(url_for('auth.login'))
	unset_jwt_cookies(response)
	return response

app/routes/control.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_jwt_extended import jwt_required, current_user

from app.models import db
from app.models.user import User


bp = Blueprint('control', __name__, url_prefix='/dashboard')

@bp.route("/", methods=['GET','POST'])
@jwt_required()
def dashboard():
	return render_template("dashboard.html")

## ***************Users********************

@bp.route("/users", methods=['GET'])
@jwt_required()
def users():
	return render_template("users.html")

@bp.route("/users/<int:user_id>", methods=['GET','POST'])
@jwt_required()
def edit_user(user_id):
	return render_template("edit_user.html", id=user_id, user_id=current_user.id)

@bp.route("/new_user", methods=['GET'])
@jwt_required()
def new_user():
	return render_template("new_user.html")

app/routes/index.py
from flask import *
from flask_jwt_extended import jwt_required

from app.models.user import User

bp = Blueprint('index', __name__)

@bp.route("/", methods=['GET', 'POST'])
@jwt_required(optional=True)
def index():
    return render_template("welcome.html")

app/templates/auth.html
{% extends "base.html" %}

{% block title%} {{ title }} {% endblock %}

{% block content%}
<div>
	<div>
		{% with messages = get_flashed_messages(with_categories=true) %}
			<!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
			{% if messages %}
				{% for category, message in messages %}
					<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %}

		<form id="login-form" action="{{url_for('auth.login')}}" method="POST" class="card-body">
			<div class="form-group mb-3">
				<h1>Login</h1>
			</div>


			<div class="form-group mb-3">
				{{ form.username(class_="form-control",placeholder="Username")}}
			</div>

			<div class="form-group mb-3">
				{{ form.password(class_="form-control",placeholder="Password")}}
			</div>

			<input id="submit-form" type="submit" value="Submit" class="save">

			</p>

		</form>
	</div>
	<a href="{{url_for('index.index')}}">
		<button class="back">back</button>
	</a>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title%} {{ title }} {% endblock %}</title>
		<link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
	</head>

	{% block styles %}
	<body>
		{% block content%}
		{% endblock %}
		<script src="{{url_for('static', filename='main.js')}}"></script>
	</body>
	{% endblock %}
</html>

app/templates/base_dashboard.html
{% extends "base.html" %}
{% block title%} {{ title }} {% endblock %}

{% block content%}
<script src="{{url_for('static', filename='jwt.js')}}"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<div id="daschboard">
	{% block daschboard_content%}{% endblock %}
</div>
{% endblock %}

app/templates/dashboard.html
{% extends "base_dashboard.html" %}
{% block title%} {{ title }} {% endblock %}

{% block daschboard_content%}
<h1>Dashboard</h1>
<p><strong>Username:</strong> {{current_user.name}}</p>

<ul>
	<li>
		<a href="{{url_for('control.users')}}">Users</a>
	</li>
</ul>

<a href="{{url_for('auth.logout')}}" class="btn btn-primary">Logout</a>
{% endblock %}

app/templates/edit_user.html
{% extends "base_dashboard.html" %}
{% block title%} {{ title }} {% endblock %}

{% block daschboard_content%}
<h1>Edit User</h1>
<div id="info" style="display: none;"></div>
<form id="edit-user-form" data-id="{{id}}">
	<p>
		<label for="name">Username:</label>
		<input type="text" name="name" id="name">
	</p>
	<p>
		<label for="email">E-Mail:</label>
		<input type="text" name="email" id="email">
	</p>
	<p>
		<label for="password">Password:</label>
		<input type="password" name="password" id="password">
	</p>
	<p>
		<input type="submit" value="Save">
	</p>
</form>

<a href="{{url_for('control.users')}}" class="btn btn-primary">
	Back
</a>

<script src="/static/edit_user.js"></script>
{% endblock %}

app/templates/new_user.html
{% extends "base_dashboard.html" %}
{% block title%} {{ title }} {% endblock %}

{% block daschboard_content%}
<h1>New User</h1>
<div id="info" style="display: none;"></div>
<form id="new-user-form">
	<p>
		<label for="username">Username:</label>
		<input type="text" name="name" id="name">
	</p>
	<p>
		<label for="email">E-Mail:</label>
		<input type="text" name="email" id="email">
	</p>
	<p>
		<label for="password">Password:</label>
		<input type="password" name="password" id="password">
	</p>
	<p>
		<input type="submit" value="Save">
	</p>
</form>

<a href="{{url_for('control.users')}}" class="btn btn-primary">
	Back
</a>
<script src="/static/new_user.js"></script>
{% endblock %}

app/templates/users.html
{% extends "base_dashboard.html" %}
{% block title%} {{ title }} {% endblock %}

{% block daschboard_content%}
<h1>Users</h1>

<table id="user-list" class="dashboard-list">
	<thead>
		<tr>
			<th>Name</th>
			<th>E-Mail</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody></tbody>
</table>

<a href="{{url_for('control.new_user')}}">
	New User
</a>

<a href="{{url_for('control.dashboard')}}">
	Back
</a>

<div id="remove-user-popup" class="overlay" style="display: none;">
	<div class="popup">
		<h2>Remove User</h2>

		<p>
			Do you wish to remove <span id="remove-user-name" class="remove-name"></span>?
		</p>

		<div class="controls">
			<a id="remove-user" href="#" class="btn btn-danger">
				Remove
			</a> 

			<a id="remove-user-cancel" href="#" class="btn btn-secondary">
				Cancel
			</a>
		</div>
	</div>
</div>
<script src="/static/users.js"></script>
{% endblock %}

app/templates/welcome.html
{% extends "base.html" %}
{% block title%} {{ title }} {% endblock %}
{% block content%}
<div>
	<h1>Main</h2>
	<p>The Main Page</p>
	<a href="{{url_for('auth.login')}}">Login</a>
</div>
{% endblock %}